theme: jekyll-theme-minimal
title: Maria Korochkina's home page
description: Feel free to bookmark this to keep an eye on my projects

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: "m.png"

email: maria dot korochkina at hdr dot mq dot edu dot au
